
"use strict";
let heading=document.createElement("h1");
heading.id="title";
let form1=document.createElement("form");
form1.id="form";
let instruction=document.createElement("p");
instruction.id="description";
let label1=document.createElement("label");
let input1=document.createElement("textarea");
let space1=document.createElement("br");
let label2=document.createElement("label");
let input2=document.createElement("textarea");
let space2=document.createElement("br");
let label3=document.createElement("label");
let input3=document.createElement("textarea");
let space3=document.createElement("br");
let label4=document.createElement("label");
let input4=document.createElement("input");
let space4=document.createElement("br");
let label5=document.createElement("label");
let input50=document.createElement("input");
let input51=document.createElement("input");
let input52=document.createElement("input");
let label50=document.createElement("label");
let label51=document.createElement("label");
let label52=document.createElement("label");
let space5=document.createElement("br");
let label6=document.createElement("label");
let space6=document.createElement("br");
let input60=document.createElement("input");
let label60=document.createElement("label");
let space60=document.createElement("br");
let input61=document.createElement("input");
let label61=document.createElement("label");
let space61=document.createElement("br");
let input62=document.createElement("input");
let label62=document.createElement("label");
let space62=document.createElement("br");
let input63=document.createElement("input");
let label63=document.createElement("label");
let space63=document.createElement("br");
let input64=document.createElement("input");
let label64=document.createElement("label");
let space64=document.createElement("br");
let label7=document.createElement("label");
let input7=document.createElement("input");  
let space7=document.createElement("br");
let label8=document.createElement("label");
let input8=document.createElement("input");
let Submit=document.createElement("button");
let division=document.createElement("div");
division.class="container";   
let table=document.createElement("table");
table.class="table";
table.id="table1";
const rowheader=table.insertRow();
rowheader.id="rowheader";
const headerCol1=rowheader.insertCell();
headerCol1.id="hcol1";
const headerCol2=rowheader.insertCell();
headerCol2.id="hcol2";
const headerCol3=rowheader.insertCell();
headerCol3.id="hcol3";
const headerCol4=rowheader.insertCell();
headerCol4.id="hcol4";
const headerCol5=rowheader.insertCell();
headerCol5.id="hcol5";
const headerCol6=rowheader.insertCell();
headerCol6.id="hcol6";
const headerCol7=rowheader.insertCell();
headerCol7.id="hcol7";
const headerCol8=rowheader.insertCell();
headerCol8.id="hcol8";
document.body.appendChild(heading);
document.body.appendChild(instruction);
document.body.appendChild(form1);
form1.appendChild(label1);
form1.appendChild(input1);
form1.appendChild(space1);
form1.appendChild(label2);
form1.appendChild(input2);
form1.appendChild(space2);
form1.appendChild(label3);
form1.appendChild(input3);
form1.appendChild(space3);
form1.appendChild(label4);
form1.appendChild(input4);
form1.appendChild(space4);
form1.appendChild(label5);
form1.appendChild(input50);
form1.appendChild(label50);
form1.appendChild(input51);
form1.appendChild(label51);
form1.appendChild(input52);
form1.appendChild(label52);
form1.appendChild(space5);
form1.appendChild(label6);
form1.appendChild(space6);
form1.appendChild(input60);
form1.appendChild(label60);
form1.appendChild(space60);
form1.appendChild(input61);
form1.appendChild(label61);
form1.appendChild(space61);
form1.appendChild(input62);
form1.appendChild(label62);
form1.appendChild(space62);
form1.appendChild(input63);
form1.appendChild(label63);
form1.appendChild(space63);
form1.appendChild(input64);
form1.appendChild(label64);
form1.appendChild(space64);
form1.appendChild(label7);
form1.appendChild(input7);
form1.appendChild(space7);
form1.appendChild(label8);
form1.appendChild(input8); 
form1.appendChild(Submit);
document.body.appendChild(division);
division.appendChild(table);
heading.innerHTML="FOOD REVIEW FORM";
instruction.innerHTML="Please fill up the details below"
label1.innerHTML="First name";
label2.innerHTML="Last name";
label3.innerHTML="Address";
label4.innerHTML="Pincode";
label5.innerHTML="Gender";
label50.innerHTML="Male";
label51.innerHTML="Female";
label52.innerHTML="Other";
label6.innerHTML="Choice of Food (must choose at least 2 out of 5 options)";
label60.innerHTML="Continental Food";
label61.innerHTML="South Indian Food";
label62.innerHTML="Bangali Food";
label63.innerHTML="Muglai Food";
label64.innerHTML="Chinese Food";
label7.innerHTML="State";
label8.innerHTML="Country";
label1.id="Firstname";
label2.id="Lastname";
label3.id="Address";
label4.id="Pincode";
label5.id="Genders";
label6.id="Choice";
label7.id="State";
label8.id="Country";
input1.id="first-name";
input1.placeholder="Type your first name";
input2.id="last-name";
input2.placeholder="Type your last name";
input3.id="address";
input3.placeholder="Type your address"
input4.type="text";
input4.id="pincode";
input4.placeholder="Enter pincode";
input50.type="radio";
input50.id="male";
input50.name="gender";
input50.value="Male";
input51.type="radio";
input51.id="female";
input51.name="gender";
input51.value="Female";
input52.type="radio";
input52.id="other";
input52.name="gender";
input52.value="Other";
input60.type="radio";
input60.name="cFood";
input60.value="Continental Food";
input61.type="radio";
input61.name="sFood";
input61.value="South Indian Food";
input62.type="radio";
input62.name="bFood";
input62.value="Bangali Food";
input63.type="radio";
input63.name="mFood";
input63.value="Muglai Food";
input64.type="radio";
input64.name="chFood";
input64.value="Chinese Food";
input7.type="text";
input7.id="state";
input7.placeholder="Enter the State"
input8.type="text";
input8.id="country";
input8.placeholder="Enter the country";
Submit.type="button";
Submit.name="button";
Submit.class="btn";
Submit.innerHTML="Submit";
Submit.id="submit";
headerCol1.innerHTML="First name";
headerCol2.innerHTML="Last name";
headerCol3.innerHTML="Address";
headerCol4.innerHTML="Pincode";
headerCol5.innerHTML="Gender";
headerCol6.innerHTML="Food";
headerCol7.innerHTML="State";
headerCol8.innerHTML="Country";

document.getElementById("submit").onclick=function(){

    document.getElementById("table1").style.display="block";
    const row=table.insertRow();
    row.id="line";
    const col1=row.insertCell();
    col1.id="col1";
    const col2=row.insertCell();
    col2.id="col2";
    const col3=row.insertCell();
    col3.id="col3";
    const col4=row.insertCell();
    col4.id="col4";
    const col5=row.insertCell();
    col5.id="col5";
    const col6=row.insertCell();
    col6.id="col6";
    const col7=row.insertCell();
    col7.id="col7";
    const col8=row.insertCell();
    col8.id="col8"; 
    col1.innerHTML=input1.value;
    col2.innerHTML=input2.value;
    col3.innerHTML=input3.value;
    col4.innerHTML=input4.value;
   if(input50.checked)
        col5.innerHTML=input50.value;
        if(input51.checked)
        col5.innerHTML=input51.value;
        if(input52.checked)
        col5.innerHTML=input52.value;
    col6.innerHTML="";
    if(input60.checked)
    col6.innerHTML+=`${input60.value}<br>`;
    if(input61.checked)
    col6.innerHTML+=`${input61.value}<br>`;
    if(input62.checked)
    col6.innerHTML+=`${input62.value}<br>`;
    if(input63.checked)
    col6.innerHTML+=`${input63.value}<br>`;
    if(input64.checked)
    col6.innerHTML+=`${input64.value}<br>`;

    col7.innerHTML=input7.value;
    col8.innerHTML=input8.value;
    form1.reset();
    return false;
}






